org: dinushab14
app: freely-take-home-test
service: freely-take-home-test

frameworkVersion: '3'

package:
  patterns:
    - '!src/**'
    - '!__tests__/**'
    - '!tsconfig.json'
    - '!README.md'
    - '!jest.config.json'

custom:
  snsTopic: userRegistrations

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    USERS_TABLE: ${self:service}-usersTable-${sls:stage}
    SNS_REGION: ${aws:region}
    SNS_TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.snsTopic}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-usersTable-${sls:stage}"
        - Effect: Allow
          Action:
            - SNS:Publish
          Resource: "arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.snsTopic}"

functions:
  registerUser:
    handler: dist/handlers/users.registerUser
    events:
      - sns: ${self:custom.snsTopic}

  createUser:
    handler: dist/handlers/users.createUser
    events:
      - httpApi:
          path: /users
          method: post

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-usersTable-${sls:stage}
